DROP TABLE IF EXISTS `sld_favorites`;

CREATE TABLE `sld_favorites` (
  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `ENTITY_TYPE` varchar(45) NOT NULL DEFAULT 'IBLOCK_ELEMENT',
  `ENTITY_ID` int(11) unsigned NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UNIQUE_ROW` (`USER_ID`,`ENTITY_TYPE`,`ENTITY_ID`),
  KEY `FK_USER_INDEX` (`USER_ID`),
  CONSTRAINT `FK_USER` FOREIGN KEY (`USER_ID`) REFERENCES `b_user` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;
